# name: learn1
# description: "A new Flutter project."
# publish_to: 'none'
# version: 0.1.0

# environment:
#   sdk: '>=3.2.6 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   auto_size_text: ^3.0.0
#   intl: ^0.17.0
#   isar: ^3.1.0+1
#   isar_flutter_libs: ^3.1.0+1
#   provider: ^6.1.1
#   path_provider: ^2.1.3
#   flutter_staggered_grid_view: ^0.6.2
#   flutter_native_splash: ^2.4.1
  

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0
#   isar_generator: ^3.1.0+1
#   build_runner: ^2.4.9
#   change_app_package_name: ^1.4.0
#   flutter_launcher_icons: "^0.14.0"

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/applogo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "assets/applogo.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "assets/applogo.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "assets/applogo.png"

# flutter:
#   uses-material-design: true


#   assets:
#     - assets/splash_screen.png

# flutter_native_splash:
#   image: assets/splash_screen.png  # Path to your splash image
#   color: "#ffffff"                 # Background color (fallback if the image has transparency)
#   android: true
#   ios: true
#   web: false
#   android_gravity: center          # Align the image to the center (you can adjust alignment as needed)
#   ios_content_mode: center         # Center the image on iOS devices

name: learn1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  provider: 
  path_provider: ^2.1.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_native_splash: ^2.4.1
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.1.0
  win32: ^5.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: "^0.14.0"
  shared_preferences: ^2.0.13  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/applogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/applogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/applogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/applogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/splash_screen.png

# Move the flutter_native_splash section outside of the flutter section
flutter_native_splash:
  image: assets/splash_screen.png  # Path to your splash image
  color: "#ffffff"                 # Background color (fallback if the image has transparency)
  android: true
  ios: true
  web: false
  android_gravity: fill            # Scale the image to fill the screen on Android
  ios_content_mode: scaleToFill    # Scale the image to fill the screen on iOS
